# Generated by Django 3.2.9 on 2021-12-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
